apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todoapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: karma792/todoapp:1.0
          ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todoapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

