apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: django-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-todo-web-k8s
        image: karma792/todo:v2
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "chmod +x /todoapp/migrate.sh && sh /todoapp/migrate.sh && /todoapp/entrypoint.sh"]
        envFrom:
          - secretRef:
              name: django-k8s-web-prod-env
        env:
          - name: PORT
            value: "8002"
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                 name: postgresdb-configmap
                 key: database_url
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8002
  selector:
    app: django-k8s-web-deployment
